ENV = "prod"

# MYSQL ValUEs
MYSQL_STORAGE           = 100
MYSQL_ENGINE_VERSION    = "5.7"
MYSQL_INSTANCE_TYPE     = "db.t3.medium"

# DOCDB ValUEs
DOCDB_INSTANCE_TYPE     = "db.t3.large"
DOCDB_INSTANCE_COUNT    = 3

# REDIS Values
REDIS_INSTANCE_TYPE  = "cache.t3.small"
REDIS_PORT           = 6379
REDIS_ENGINE_VERSION = "6.x""
REDIS_INSTANCE_COUNT = 1
