ENV = "prod"

# MYSQL ValUEs
MYSQL_STORAGE           = 100
MYSQL_ENGINE_VERSION    = "5.7"
MYSQL_INSTANCE_TYPE     = "db.t3.medium"

# DOCDB ValUEs
DOCDB_INSTANCE_TYPE     = "db.t3.large"
DOCDB_INSTANCE_COUNT    = 3